include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # ⚡ Efisiensi & performa (umum + Flutter UI)
    - avoid_unnecessary_containers
    - avoid_returning_null_for_void
    - avoid_init_to_null
    - prefer_final_fields
    - prefer_final_locals
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_spread_collections
    - prefer_collection_literals
    - unnecessary_const
    - unnecessary_late
    - unnecessary_string_interpolations
    - avoid_function_literals_in_foreach_calls
    - avoid_redundant_argument_values
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_contains
    - sized_box_for_whitespace
    - use_colored_box
    - use_decorated_box
    - use_string_buffers
    - avoid_slow_async_io
    - avoid_double_and_int_checks
    - use_key_in_widget_constructors
    - use_super_parameters
    - prefer_mixin
    - prefer_final_in_for_each
    - sort_constructors_first
    - use_named_constants
    - curly_braces_in_flow_control_structures
    - prefer_relative_imports
    - require_trailing_commas

    # 🛡️ Keamanan & bug prevention
    - avoid_empty_else
    - avoid_print
    - cancel_subscriptions
    - close_sinks
    - hash_and_equals
    - no_logic_in_create_state
    - throw_in_finally
    - use_rethrow_when_possible
    - avoid_types_as_parameter_names
    - valid_regexps
    - await_only_futures
    - avoid_null_checks_in_equality_operators
    - avoid_field_initializers_in_const_classes
    - avoid_returning_this

    # 🧹 Kebersihan kode & gaya penulisan
    - unnecessary_new
