// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXEBS2BFkWxPxP3pilg2vow5ZLP1efMoU',
    appId: '1:533114573770:web:2421186589d8e992387533',
    messagingSenderId: '533114573770',
    projectId: 'bloom-88be1',
    authDomain: 'bloom-88be1.firebaseapp.com',
    databaseURL: 'https://bloom-88be1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bloom-88be1.appspot.com',
    measurementId: 'G-TRXG4NJH3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnXmS-HUXUtWTiXLbW46er3oxl3Bxf9MY',
    appId: '1:533114573770:android:7f75863faf8c4f86387533',
    messagingSenderId: '533114573770',
    projectId: 'bloom-88be1',
    databaseURL: 'https://bloom-88be1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bloom-88be1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrZFVgxBFG5YrdpJoS6WRchLRk7BiUDZc',
    appId: '1:533114573770:ios:79d0ed23f21f8731387533',
    messagingSenderId: '533114573770',
    projectId: 'bloom-88be1',
    databaseURL: 'https://bloom-88be1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bloom-88be1.appspot.com',
    androidClientId: '533114573770-m2bg413eb2vp2gqg3ub4cfv467nv8m6h.apps.googleusercontent.com',
    iosClientId: '533114573770-2v8go7bkk6s9lp139idq667h5uoosic1.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloom',
  );
}
